spring.application.name=MusicPlaylist
spring.datasource.url=jdbc:h2:mem:musicplaylist;DB_CLOSE_DELAY=-1;MODE=LEGACY
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=9999
app.bootstrap-admin.username=admin
app.bootstrap-admin.password=admin123
app.bootstrap-admin.name=System
app.bootstrap-admin.surname=Administrator
